server:
    epochs: 200

client:
    qnt: 20
    chosen: 3
    training:
        epochs: 3
        batch_size: 64

storage:
    data:
        path: '../storage/data2'
    model:
        path: '../storage/model/fedavg'
        name:
            server: 'model_server_{}.pt' # {0} - iteration
            client: 'model_client_{}_{}.pt' # {0} - iteration, {1} - client id

seed: 12345