server:
    epochs: 200
    knowledge_transfer:
        client_qnt: 3
        epochs: 10
        batch_size: 64
        temperature: 2 #1
        soft_target_loss_weight: 0.8
        criterion_loss_weight: 0.2

client:
    qnt: 20
    chosen: 3
    models:
        - mobilenetv2
        - resnet
        - simple_cnn
    training:
        epochs: 5
        batch_size: 64

storage:
    data:
        path: '../storage/data2'
    model:
        path: '../storage/model/feddf'
        name:
            server: 'model_server_{0}_{1}.pt' # {0} - type, {1} - round
            client: 'model_client_{0}_{1}.pt' # {0} - round, {1} - client id

seed: 12345