server:
    epochs: 100

client:
    qnt: 5
    chosen: 3
    training:
        epochs: 5
        batch_size: 20

storage:
    data:
        path: '../storage/data'
    model:
        path: '../storage/model/fedavg'
        name:
            server: 'model_server_{}.pt' # {0} - iteration
            client: 'model_client_{}_{}.pt' # {0} - iteration, {1} - client id

seed: 12345