cloud:
    epochs: 200

edge:
    qnt: 5
    training:
        iterations: 3

client:
    qnt: 4
    training:
        epochs: 3
        batch_size: 64

storage:
    data:
        path: '../storage/data2'
    model:
        path: '../storage/model/hierfavg'
        name:
            cloud: 'model_cloud_{0}.pt' # {0} - round
            edge: 'model_edge_{0}_{1}_{2}.pt' # {0} - round, {1} - iteration, {1} - edge id
            client: 'model_client_{0}_{1}_{2}.pt' # {0} - round, {1} - iteration,  {2} - client id

seed: 12345