cloud:
    address: '127.0.0.1'
    port: 12345

edge:
    address: '127.0.0.1'
    port: 12350
    qnt: 2
    training:
        iterations_per_round: 1

client:
    qnt: 1
    training:
        epochs_per_iteration: 1

storage:
    data:
        path: '../storage/data'
    model:
        path: '../storage/model/hierfavg'
        name:
            cloud: 'model_cloud_{0}.pt' # {0} - iteration
            edge: 'model_edge_{0}_{1}.pt' # {0} - iteration, {1} - edge id
            client: 'model_client_{0}_{1}.pt' # {0} - iteration, {1} - client id

seed: 12345